language: cpp
cache:
  - apt
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
install:
#  - env
#  - make pip
  - make update
  - make build
  - sudo make install
# command to run tests
script:
  - make autobuild-tests
# package dependencies
before_install:
  #- env
  #- sudo -E env
  - sudo apt-get update -y -qq
  - sudo -E make python-deps
  - sudo -E make autobuild-deps
